spring.application.name=flash

spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com/v1beta/openai/chat/completions
spring.ai.openai.api-key=AIzaSyDunA_v_xhS_l14nuZjcQdAxnNigzDn8KY
spring.ai.openai.chat.options.model=gemini-2.0-flash