spring.application.name=flash

spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com/v1beta/openai/chat/completions

#https://aistudio.google.com/app/api-keys?_gl=1*kdjzi*_ga*MzI3NDQzMDIuMTc3Nzc3MTU1NA..*_ga_P1DBVKWT6V*czE3Nzc3NzE1NTQkbzEkZzAkdDE3Nzc3NzE1ODQkajMwJGwwJGgyMDk1MTI3NDMx&project=gen-lang-client-0903506764
spring.ai.openai.api-key=

spring.ai.openai.chat.options.model=gemini-2.0-flash